before_install:
    - mkdir $TRAVIS_BUILD_DIR/lib
    - curl -o $TRAVIS_BUILD_DIR/lib/GeneralLib.jar https://api.spiget.org/v2/resources/25348/download
    - curl -o $TRAVIS_BUILD_DIR/lib/Kingdoms.jar https://api.spiget.org/v2/resources/6392/download
    - curl -o $TRAVIS_BUILD_DIR/lib/Residence.jar http://ltcraft.lt/Residence/files/Residence4.7.0.5.jar
    - curl -o $TRAVIS_BUILD_DIR/lib/RedProtect.jar https://api.spiget.org/v2/resources/15841/download
notifications:
  email: false
language: java
jdk:
- oraclejdk8

before_deploy:
    - echo -e "Starting to tag commit.\n"
    - git config --global user.email "builds@travis-ci.org"
    - git config --global user.name "Travis CI"
    - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
    - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
    - git push https://$GITPERM@github.com/$TRAVIS_REPO_SLUG $GIT_TAG
    - git fetch origin
    - echo -e "Finished with tagging.\n"

deploy:
    provider: releases
    prerelease: true
    skip_cleanup: true
    name: "RandomCoords Build $TRAVIS_BUILD_NUMBER"
    body: "## Build $TRAVIS_BUILD_NUMBER\nGenerated by Travis-CI on $(date +'%F-%T').\nBranch: [$TRAVIS_BRANCH](https://github.com/$TRAVIS_REPO_SLUG/tree/$TRAVIS_BRANCH)\nCommitmessage: [$TRAVIS_COMMIT_MESSAGE](https://github.com/$TRAVIS_REPO_SLUG/commit/$TRAVIS_COMMIT)\nCommit ID: $TRAVIS_COMMIT"
    draft: false
    api_key: $GITPERM
    file:
        - "target/RandomCoordinates-2.1.0.jar"
    on:
        tags: false
        all_branches: true
        repo: PHENOMICAL/RandomCoordinatesV2

branches:
    only:
    - master