#General Settings
RandomOrg: false
ChunkLoader: false
Metrics: true
debug: false
Experimental: true
BannedWorlds:
 - world_the_end
CircleRadiusDefault: false
CircleRadiusWorlds:
  - example

#Update Settings
UpdateCheckOnStartup: true
NotifyPlayerOnJoin: true
InformExperimental: true
InformBuildsAhead: true
 
#Teleport Settings
MaxCoordinate: 5000
MinCoordinate: 0
StopOnMove: true
StopOnCombat: true
Sound: ENTITY_ENDERDRAGON_FLAP
Effect: ENDER_SIGNAL

# Teleport Method, Can be random or warps
Command: random
All: random
Others: random
Portals: random
Signs: random
Join: random

#Cooldown Settings
CooldownTime: 5
CooldownApplys:
 - Command
 - Warps
 
InvulTime: 10

#Wait before Teleport Settings
TimeBeforeTeleport: 5
TimeBeforeApplys:
 - Command
 - Warps
 - Signs
 
#Location finding Settings
MaxAttempts: 20
AttemptsPerTick: 1
TicksBetweenAttempts: 3
InformPlayerAfterAttempts: 50

#Safety Checks
CheckingRadius: 100
Factions: false
GriefPrevention: false
AvoidPlayers: false
Towny: false
WorldBorder: false
RedProtect: false
Kingdoms: false
VanillaBorder: true
SkyBlock: false
Residence: false
PlotSquared: false
WorldGuard: false
Regions:
 - example

#On Join Features
OnJoin: false
OnJoinWorlds:
 - example
OnJoinCommand: none
BonusChest: false
BonusChestItems:
 - WOOD_SWORD

#Economy Settings
CommandCost: 0
PortalCost: 0

#Warp Settings
WarpCrossWorld: true

#Limiter Settings
Limit: 0
LimiterApplys:
 - Command
 - Warps