name: RandomCoords
main: com.jolbol1.RandomCoordinates.RandomCoords
version: 2.1.0-RELEASE
website: http://bukkit.org
author: Jolbol1
authors: [Jolbol1, PHENOMICAL]
softdepend: [Factions, MassiveCore, WorldEdit, WorldBorder, Vault, WorldGuard, Essentials, Towny, Residence, RedProtect, Kingdoms, GriefPrevention, PlotSquared]
description: >
             Get away quick with a random coordinate.
commands:
  rc:
    description: Teleport to a random coordinate.
    usage: /<command>
    aliases: [randomcoord, randomcoords, randomcoordinates, wild, rtp]