name: RandomCoords
main: com.jolbol1.RandomCoordinates.RandomCoords
version: 0.0.1-ALPHA
website: http://bukkit.org
author: Jolbol1
softdepend: [Factions, MassiveCore, WorldEdit, WorldBorder, Vault, WorldGuard]
description: >
             Get away quick with a random coordinate.
commands:
  rc:
    description: Teleport to a random coordinate.
    usage: /<command>
    aliases: [randomcoord, randomcoords, randomcoordinates]